#+STARTUP: indent overview
#+TITLE:     Workflow Assistant - Internals
#+AUTHOR:    Henrik Andersson
#+EMAIL:     hean01 AT gmail.com
#+DATE:      2013-09-14 Sat
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

* Workflow Assistant - Internals
** Overview
The application consist of two activities and a service. The service
holds all logics and data where activities are simple viewers.  The
two activities are managing of workflows and the progress of a current
workflow.
** Classes
*** WFAManagerActivity
This is the main activity, responsible to start the service and be the
manager of workflows.
*** WFAProgressActivity
This activity is the visual progress of an ongoing workflow.
*** WFAPreferencesActivity
This activity shows the preferences of the application and extends the
=android.preference.PreferenceActivity=. The preferences is defined in
the resource =res/xml/preferences.xml=.
*** WFAService
The service is the core of /Workflow Assitant/, it holds all logics and data.
*** Workflow
A workflow consists of several tasks in a specific order. A workflow
has a name, description and a state. States are /READY/, /RUNNING/ and
/FINISHED/.
*** Workflow Observer
This is a observer interface for a workflow.
*** WorkflowTask
A task has a description, length of time and a state. States are
/READY/, /RUNNING/ and /FINISHED/.
*** WorkflowManager
The workflow manager is responsible for loading, storing of
workflows. This class is the only class responsible for instantiating
Workflow objects.
*** ProgressView
This class implements the actual progress view which is shown in
WFAProgressActivity.
** Classdiagram

#+HEADER: :file class_diagram.svg
#+BEGIN_SRC plantuml
skinparam backgroundColor #FFFFFF
hide circle

skinparam class {
  AttributeIconSize 0
  ArrowColor Black
  BackgroundColor White
  BorderColor Black
}

package com.github.hean01.workflowassistant {
class WFAService {
}

class WFAManagerActivity {
}

class WFAPreferencesActivity {
}

class WFAProgressActivity {
}

class ProgressView {
}

class WorkflowManager {
  + initialize()
  # workflows : List<Workflow>
}

class Workflow {
 + initialize(String)
 + clock(int)
 + reset()
 + isFinished() : boolean
 + task() : WorkflowTask
 + addObserver(WorkflowObserver)
 + removeObserver(WorkflowObserver)
 + notifyObserversOnChange()
 + name : String
 + description : String
 # notifyObserverOnNewTask()
 # notifyObserverOnTaskChange()
 - _observers : HashSet
 - _tasks : List<WorkflowTask>
}

interface WorkflowObserver {
 + onTask(WorkflowTask)
 + onChange(WorkflowTask)
}

class WorkflowTask {
  + description : String
  + isFinished() : boolean
  + reset()
  + clock()
}
}



WFAProgressActivity .. WFAService
WFAProgressActivity o-- ProgressView
WFAManagerActivity .. WFAService
WFAPreferencesActivity .. WFAManagerActivity
WFAPreferencesActivity <|-- android.preference.PreferenceActivity
WFAPreferencesActivity o-- android.preference.SharedPreferences : _preferences
WFAManagerActivity <|-- android.app.Activity
WorkflowObserver <|.. WFAProgressActivity
WFAService <|-- android.app.Service
WFAService o-- WorkflowManager
WFAService o-- android.preference.SharedPreferences : _preferences
WorkflowManager "1" o-- "0..*" Workflow
Workflow "1" o-- "0..*" WorkflowObserver : _observers
Workflow "1" o-- "1..*" WorkflowTask : _tasks
Workflow o-- android.preference.SharedPreferences : _preferences
ProgressView <|-- android.graphics.View
#+END_SRC
